### ISSUE TITLE
How to see multiple error msg of same field

### ISSUE THREAD

**Issue by ravindrasinghinbox** [bitnbytesio/node-input-validator#13]
{
     "email": {
            "message": "The email must be a number.",
            "rule": "numeric"
        },
}
=> Expected
"email": {
            "message": ["The email must not containe ...", "The email must be a valid."],
            "rule": "email"
        },

**Comment by artisangang** [comment]
Currently library break the rules loop if any of rule failed on validate against input. I will plan this on next release. Thanks for your inputs.

**Comment by bitnbytesio** [comment]
Multiple errors feature added in next release.

https://www.npmjs.com/package/node-input-validator/v/4.0.0-rc4
