### ISSUE TITLE
Validation of stacked arrays

### ISSUE THREAD

**Issue by FireEmerald** [bitnbytesio/node-input-validator#18]
Am I wrong or is a syntax like this with two arrays not possible to validate?
``` js
'submitted': 'required|array',
'submitted.*.id': 'required',
'submitted.*.items': 'required|array',
'submitted.*.items.*.id': 'required|digitsBetween:1,20',
'submitted.*.items.*.name': 'required',
```

Error:
``` js
{
  "message": "The submitted.0.items.*.id field is mandatory.",
  "rule": "required"
}
```
The field from the message exists multiple times in every submitted entry.

**Comment by bitnbytesio** [comment]
In earlier version (3.x), this is not possible.
Fixed in next release.
https://www.npmjs.com/package/node-input-validator/v/4.0.0-rc4
