### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by FireEmerald** [bitnbytesio/node-input-validator#19]
I expected that the `check()` method does **not** throw any errors on validation.

But I got sometimes a `"Cannot read property 'length' of undefined"` error, is this expected?

**Line:**
https://github.com/artisangang/node-input-validator/blob/4971077fbe13b639219ff87a268c814f16130b00/src/validator.js#L33

**Code:**
```
let fields = JSON.parse('[{"item": "1"}, {"item": "2"}]');
let validator = new v(fields, {
    submitted: 'required|array',
    'items.*': 'required'
});
let matched = await validator.check();
```

https://runkit.com/embed/ihncwxfh4e6s

**Comment by bitnbytesio** [comment]
This is because of array as top level input. Ver 3.7 suppress this. 
Currently package does not validate array in top level input.
