### ISSUE TITLE
Array as root element

### ISSUE THREAD

**Issue by FireEmerald** [bitnbytesio/node-input-validator#20]
Is it possible to validate a structure like this, where the **root** element should be an array?

``` js
let input = [
              { id: 1, name: 'test' },
              { id: 2, name: 'this' }
            ];
```

**Comment by bitnbytesio** [comment]
No, you need to wrap it in object.

**Comment by FireEmerald** [comment]
@bitnbytesio What's the reason for not supporting arrays on root level?

**Comment by bitnbytesio** [comment]
Didn't think of it. may thought for this feature in future release or you
could submit PR.

**Comment by FireEmerald** [comment]
I will take a look at it when I find some time...

**Comment by bitnbytesio** [comment]
Root level support added from:
https://www.npmjs.com/package/node-input-validator/v/3.8.0
