### ISSUE TITLE
validation with multiple object is not working

### ISSUE THREAD

**Issue by ShailendraGICR** [bitnbytesio/node-input-validator#21]
Hi, iI want to implement this rule but it's not working at all

`var valid = {
        email: [
            {
                rule:required,
                message:'The email field is required.'
            },
        ],
        password: [
            {
                rule:required,
                message:'The password field is required.'
            }
        ]
    };
    const v = new Validator(request.body, valid);
    v.check().then((matched) => {
        console.log(matched);
        if (!matched) {
            response.status(422).send(v.errors);
        }
    });`

**Comment by bitnbytesio** [comment]
Please check documentation.
```javascript
const v = new Validator(
  {/*request.body*/}, // inputs here
  { // rules
    email: 'required|email',
    password: 'required'
  },
  { //messages
    email: 'The email field is required.',
    password: 'The password field is required.',
  }
); 
v.check().then((matched) => {
   console.log(matched); 
   console.log(v.errors);
});
```

If still an issue, share node-input-validator version your are using and proper code snippet.

**Comment by bitnbytesio** [comment]
Array of objects example: 
```javascript
const v = new Validator(
  {// inputs here
    parent: [
      { email: '', password: '' },
    ],
  },
  { // rules
    'parent.*.email': 'required|email',
    'parent.*.password': 'required'
  }
);
v.check().then((matched) => {
  console.log(matched);
  console.log(v.errors);
});
```
