### ISSUE TITLE
None of Alpha rules does't accept Persian and Arabic characters

### ISSUE THREAD

**Issue by ghonchesefidi** [bitnbytesio/node-input-validator#25]
None of Alpha rules like alpha,alphaDash and alphaNumeric does't accept Persian and Arabic characters.  
I will try to fix this issue and I will share my result.

**Comment by bitnbytesio** [comment]
might need to code separate rules or some kind of auto language detection.

**Comment by bitnbytesio** [comment]
From version 4.3.0

you can pass locale (as shared on <a href="https://www.npmjs.com/package/validator">https://www.npmjs.com/package/validator</a>) to alpha and alphaNumeric rule

example:

```js
new Validator(req.body, { name: 'alpha:fa-IR' })
```
