### ISSUE TITLE
.customMessages is not a function

### ISSUE THREAD

**Issue by cadhead** [bitnbytesio/node-input-validator#33]
.addCustomMessages does not work for me too.

```
const niv = require('node-input-validator');
niv.addCustomMessages({
  'service-terms-accept': 'test test'
});

module.exports = {
  Validator: niv.Validator
};
```

I guess i make mistake somewhere, but .customMessages is not existed method anyway.

**Comment by bitnbytesio** [comment]
Correct method is .addCustomMessages. 
There was a bug in this method that is fixed in v4.2.1.
