### ISSUE TITLE
Max(1000) repetation was reached 

### ISSUE THREAD

**Issue by ahmedmak96** [bitnbytesio/node-input-validator#40]
![image](https://user-images.githubusercontent.com/48183825/99661923-3c83bb00-2a6d-11eb-826a-9462e2685087.png)
as it shows here in the file "objs.js" it should be possible to customize some stuff! I tried to update the repitition variable bit it did not work because in the strNotations call there was no customize parameter passed!
I tried passing the 'this.inputs' as a second parameter in the function call in the file "validator.js" and it worked! 
![image](https://user-images.githubusercontent.com/48183825/99662324-c3389800-2a6d-11eb-9209-ebb7e3854da1.png)
*PS: 'repetition' misspelled 'repetation'

**Comment by ahmedmak96** [comment]
@bitnbytesio if any further explanation is needed, pls don't hesitate to ask!

**Comment by bitnbytesio** [comment]
thanks for reaching out.
I m surprised. I didn't not expect that someone will reach that level of nesting. I will work out this, will make this configurable,  Can you please share your request body so that I can run some performance test.

**Comment by bitnbytesio** [comment]
configurable from version 4.3.0

Example for version 4.3.0
```js
const niv = require('node-input-validator');

niv.setStrNotationRepetition(2000);
```

**Comment by ahmedmak96** [comment]
Hello,

Thanks for considering my request!  I only noticed the emails today, glad
for your help!

Have a great day
