### ISSUE TITLE
TypeError on Import in React Application

### ISSUE THREAD

**Issue by MatamandoKalilani** [bitnbytesio/node-input-validator#44]
I imported this package to a react app about 12 hours ago and it was working fine up until a few minutes ago. Now i seem to be getting a type error (" TypeError: Expected `input` to be a `Function` or `Object`, got `undefined` "). 

My project seems to run just fine only after commenting out the import statement for this package. 

Please Help

**Comment by bitnbytesio** [comment]
Hi @MatamandoKalilani  please share some code snippet to reproduce the issue. Also please mention versions of package your are using and Node.js.

Note: This packaged is not tested in browsers. It has some dependences that may not work in browser.

**Comment by MatamandoKalilani** [comment]
<img width="583" alt="2021-01-22 (3)" src="https://user-images.githubusercontent.com/63013364/105499068-9c931980-5cc9-11eb-85ca-561a56c0aed5.png">
<img width="772" alt="2021-01-22 (4)" src="https://user-images.githubusercontent.com/63013364/105499075-a026a080-5cc9-11eb-8d80-ed3c8de388b9.png">

**Comment by MatamandoKalilani** [comment]
Thank you for the timely response, highly appreciated.

I tried using this package within a simple node project and it still seems to work. It is only within my react app, that it seems not to be functioning well.  I have sent two images showing the error and where I attempted to import the package.

**Comment by bitnbytesio** [comment]
It's seems like you are using this package in browser. Package does not intend to work in browser, cause it's dependencies for rules like size and mime depends on Node.js modules. I'm working on making this library to support browser.

Beta version is out: https://www.npmjs.com/package/node-input-validator/v/5.0.0-beta.2

**How to use beta version in browser?**
```js
// Lite version of the validator
import { ValidatorLite, registerRules } from 'node-input-validator/cjs/validator-lite';

// validator messages
import { messages } from 'node-input-validator/cjs/messages/en-US.messages';
import { extend } from 'node-input-validator/cjs/messages/provider';

// import required rules that you are going to use
import { email } from 'node-input-validator/cjs/rules/email.rule';
import { alpha } from 'node-input-validator/cjs/rules/alpha.rule';
import { required } from 'node-input-validator/cjs/rules/required.rule';

// register required rules that you are going to use
registerRules({
    required,
    email,
    alpha,
});

// add messages to validator
extend(messages);

// usage example
async function validate(inputs) {
  const v = new ValidatorLite(inputs, {
    title: 'required|alpha',
    slug: 'required|email',
  });

  const passed = await v.validate();

  if (!passed) {
    this.errors = v.getErrors();
  }
}

```

Note: size and mime rules will not working in browser. Api of final release will not be same as in beta, expect minor breaking changes.

Good news is that your release bundle size will be small, as with validator lite you will be only importing stuff that you are going to use.

You can find documentation for the beta version on my website: https://bitnbytes.io/.

**Comment by MatamandoKalilani** [comment]
Understood !. 
Thank you for the support.
