### ISSUE TITLE
replace momentjs to dayjs

### ISSUE THREAD

**Issue by axmad386** [bitnbytesio/node-input-validator#45]
Hi, first I will say thank you for your work on this great library.
I just try your beta version (v5). Lite version is awesome.
I wonder, can you replace momentjs dependency to dayjs, because my project is depend on dayjs. I think it will reduce the project bundle significantly.
Or maybe there is an option like i can choose Date plugin adapter. 
Thank you

**Comment by bitnbytesio** [comment]
@axmad386  Thanks, Yes you can code a adapter for dayjs and plug it into node-input-validator. You can use any date manipulation library of your choice with node-input-validator. You just need to code a adapter. You can find example adapters here https://github.com/bitnbytesio/node-input-validator/tree/development/src/date, refer moment or date-fns adapter. 

usage
```js
const { useDateAdapter  } = require('node-input-validator');

useDateAdapter(new YourCustomDateAdapter());
```

Let me know if you need any help or have any questions regarding the implementation or interface.

**Comment by bitnbytesio** [comment]
I was trying to code adapter for dayjs. It's behavior seems strange to me. 

Specially isValid() method, take a look at https://github.com/iamkun/dayjs/issues/320#issuecomment-779019096 

However below is the example adapter, that will help you to use dayjs with node-input-validator.
```ts
import { DateAdapter } from "./contracts";

export class DayjsAdapter extends DateAdapter {
  protected dateLib: any;
  readonly FORMAT_DATE: string = 'YYYY-MM-DD';
  readonly FORMAT_DATETIME: string = 'YYYY-MM-DD HH:mm:ss';

  constructor(dateLib: any) {
    super(dateLib);
  }

  isAfter(format: string, date: Date | number | string, dateToCompare: Date | number | string): boolean {
    return this.dateLib(date, format).isAfter(this.format(dateToCompare, format));
  }

  isBefore(format: string, date: Date | number | string, dateToCompare: Date | number | string): boolean {
    return this.dateLib(date, format).isBefore(this.format(dateToCompare, format));
  }

  addDays(date: Date, days: number): Date {
    return this.dateLib(date).add(days, 'days').toDate();
  }

  subDays(date: Date, days: number): Date {
    return this.dateLib(date).subtract(days, 'days').toDate();
  }

  parseDate(date: Date | string | number, format: string): Date {
    return this.dateLib(date, format).set({
      h: 0,
      m: 0,
      s: 0,
      ms: 0,
    }).toDate();
  }

  parse(date: string, format: string, referenceDate: Date): Date {
    return this.dateLib(date, format).toDate();
  }

  isValidDateFormat(date: string, format: string | Array<string>): boolean {
    return this.dateLib(date, format).format(format) === date;
  }

  isValidIsoDateFormat(date: string): boolean {
    return false;
  }

  format(date: any, format: string): string {
    return this.dateLib(date).format(format);
  }
}

```

Note: dateISO rule is not working with this adapter, I don't know how to do it with dayjs. but most of the date rules of node-input-validator worked with existing test cases expect dateiso rule.

I recommend you to use https://github.com/date-fns/date-fns, this will also help you to control bundle size.

**Comment by axmad386** [comment]
Oh thank you very much. I will try it
