### ISSUE TITLE
[Feature] Allow Adding Implicit custom rules. 

### ISSUE THREAD

**Issue by DanielAlt** [bitnbytesio/node-input-validator#46]
Hey! 

First off, thank you so much for taking the time to program this kickass library. 

I am using your library for a project; and i found myself needing a custom implicit Validator, 

```javascript
niv.extend("requiredIfGTE", async({value, args}, validator) => {
  const otherField = args[0];
  const otherValue = args[1];

  if (!validator.validationRules.hasOwnProperty(otherField)){
    throw new Error(`${otherField} was not supplied as a validation field`);
  }

  const cmpVal = validator.validationRules[otherField].value;

  return (cmpVal >= otherValue) !!value : true;
});
```

But after testing that out i wasn't seeing the behaviour i expected. The rule was not being called, when no input was provided.  

i reviewed ```lib\validator.js``` and found that validators like 'require' need to be a part of the 'implicitRules' array @ line 12. I was wondering if you'd accept a Pull Request that will let me add custom implicit rules ?

**Comment by bitnbytesio** [comment]
@DanielAlt  thanks, your commit released under [version 4.4](https://www.npmjs.com/package/node-input-validator/v/4.4.0)
