### ISSUE TITLE
how to set custom message for specific rule?

### ISSUE THREAD

**Issue by ppatelwve** [bitnbytesio/node-input-validator#49]
Hi

How to set custom messages rule?

const checkValidator = new Validator(req.body, {
   current_password: 'required|minLength:6',
   new_password: 'required|minLength:6',
   new_confirm_password: 'required|same:new_password',
}, { new_confirm_password: 'The new password and confirm password must match.' });

every time get this meagess "The new password and confirm password must match"

how to set required message

**Comment by bitnbytesio** [comment]
```js
const checkValidator = new Validator(
    req.body,
    {
        current_password: 'required|minLength:6',
        new_password: 'required|minLength:6',
        new_confirm_password: 'required|same:new_password',
    },
    // show custom message only if given attribute failed under given rule (same)
    { 'new_confirm_password.same': 'The new password and confirm password must match.' },
);
```

Docs : https://www.npmjs.com/package/node-input-validator#add-or-modify-messages

Let me know, if you still confused
