### ISSUE TITLE
Custom async validation rule on array not always allowed to finish

### ISSUE THREAD

**Issue by itstrueimryan** [bitnbytesio/node-input-validator#51]
I have a small express app with the following custom validation rule:

```js
// USAGE
// exists:[collection]
nodeInputValidator.extend(
    'exists',
    async ({ value, args }: { value: string; args: string[] }) => {
        const collection = args[0]

        try {
            const doc = await db.collection(collection).doc(value).get()
            return doc.exists
        } catch (error) {
            return false
        }
    }
)
```

This rule checks to see if the given id exists in the db for a particular collection.  It works fine, but if I am validating an array of objects, it sometimes doesn't finish executing that object's attributes before the validator's `check` is finished. My validation logic looks like this:

```js
const testCase = req.body
const rules = {
    name: 'required|string|lengthBetween:3,30',
    presetId: 'required|string|exists:testPresets',
    additionalPresets: 'required|array',
    'additionalPresets.*.antennaPresetId': 'required|exists:testPresets',
    'additionalPresets.*.gpsPresetId': 'required|exists:testPresets',
    'additionalPresets.*.servicePresetId': 'required|exists:testPresets',
}

const validator = new Validator(testCase, rules)
const isValidPreset = await validator.check()

if (!isValidPreset) {
    res.status(422).send({ errors: validator.errors })
    return
}

req.testCase = testCase
next()
```

You can see I call the exists rule on the `presetId` attribute, and that works 100% of the time.  But the array of objects attribute validation, like `additionalPresets.*.antennaPresetId'`, for example, doesn't seem to get time to finish.  So what happens is that `next()` is called and my app returns a 200, and then the validator check fails afterwards (should have returned a 422). Sometimes it does finish, depending on how quickly it processes, but it's just up to chance.

Are there any known issues with async validation rules on this kind of setup?

**Comment by maicolbruski** [comment]
Same here:

```
const assert = require("assert");

const niv = require("../lib/index");

const { Validator } = niv;

niv.extend("asyncIn", async ({ value, args }) => {
  const results = await new Promise((resolve) => {
    setTimeout(() => {
      if (args.indexOf(value) >= 0) {
        // resolve(true);
        resolve(false);
        return;
      }

      resolve(false);
    }, 500);
  });
  return results;
});

describe("Async Rules", () => {
  it("should pass using async", async () => {
    const v = new Validator({ "status.*": ["active"] }, { status: "asyncIn:active,inactive" });

    const matched = await v.check();

    assert.equal(matched, true);
  });
});
```

![image](https://github.com/bitnbytesio/node-input-validator/assets/3951164/7b4214a7-ae23-4ad0-8d3e-333576145b25)
