### ISSUE TITLE
[question Label] Why does string with spaces assumed as false at required rule?

### ISSUE THREAD

**Issue by egorkavin** [bitnbytesio/node-input-validator#64]
I'm talking about this:
```js
// lib/util/empty.js
return !value.toString().trim()
```

Furthermore,  I don't really get why this is required:
```js
      // lib/util/Validator.js
      // if value is really empty, skip validation
      if (!validation.required && reallyEmpty(validation.value)) {
        continue;
      }
```

**Comment by niraj-khatiwada** [comment]
Oh wow I was thinking the same and I am not alone. Looks like nobody use this validation library anymore?

**Comment by niraj-khatiwada** [comment]
So after going through every available rules, 'sometimes' is the key that will make sure it cannot be empty when it is used.

new Validator({video: ""}, {video:"sometimes"}); // The field under validation is required if present.

**Comment by bitnbytesio** [comment]
@egorkavin  Yes string with spaces assumed as empty

**Comment by bitnbytesio** [comment]
Sorry guys i was too busy to check follow

**Comment by bitnbytesio** [comment]
version @4.5.0

added feature to alter this behaviour

```js
const niv = require('node-input-validator');
niv.empty.alter('reallyEmpty', () => // your logic)
```

as of version 4.5.0
- required and sometimes behaviour is same, will not allow empty string even space
- will apply rules if value have space in it (' ')

**Comment by bitnbytesio** [comment]
@egorkavin Thanks for your point
