### ISSUE TITLE
moment 2.29.3 Severity:high vulnerability

### ISSUE THREAD

**Issue by boly38** [bitnbytesio/node-input-validator#78]
Hi

first thanks for this repo: a great tool 👏 

it seems that [moment](https://www.npmjs.com/package/moment) dependency needs to be updated for security reasons
```
moment  2.18.0 - 2.29.3
Severity: high
Inefficient Regular Expression Complexity in moment - https://github.com/advisories/GHSA-wc69-rhjr-hc9g
fix available via `npm audit fix`
node_modules/moment

└─┬ node-input-validator@4.5.0
  └── moment@2.29.3
```

did you plan to update it ?
thanks

**Comment by boly38** [comment]
a new one : `file-type`
```
file-type  13.0.0 - 16.5.3
Severity: high
file-type vulnerable to Infinite Loop via malformed MKV file - https://github.com/advisories/GHSA-mhxj-85r3-2x55
fix available via `npm audit fix`
node_modules/file-type

 node-input-validator@4.5.0
  └── file-type@16.5.3
```

I'm able to workaround this by using npx-resolution but it would be great to update deps versions here.
```
  "scripts": {
    "preinstall": "npx force-resolutions",
(...)
  "resolutions": {
    "moment": "2.29.4",
    "file-type": "17.1.6"
(...)
```

**Comment by bitnbytesio** [comment]
I know it too late.
fixed: https://github.com/bitnbytesio/node-input-validator/commit/e7b59c99da99b6e773c1d67e1de641cfedd29d55
release: [4.5.1](https://www.npmjs.com/package/node-input-validator/v/4.5.1)
